plugins {
    id "net.serenity-bdd.serenity-gradle-plugin" version "5.3.2"
    id 'java'
}

defaultTasks 'clean', 'test', 'aggregate'

repositories {
    mavenCentral()
}

ext {
    slf4jVersion = '1.7.7'
    serenityCoreVersion = '5.3.2'
    junitVersion = '5.13.0'
    assertJVersion = '3.23.1'
    lombokVersion = '1.18.24'
    logbackVersion = '1.2.11'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.junit.platform:junit-platform-suite'
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.41.0'
    implementation group: 'io.cucumber', name: 'cucumber-java', version: '7.34.3'
    testImplementation 'io.cucumber:cucumber-junit-platform-engine:7.34.3'
    testImplementation 'io.github.bonigarcia:webdrivermanager:5.6.2'
    implementation group: 'com.aventstack', name: 'extentreports', version: '5.1.2'
    testImplementation "net.serenity-bdd:serenity-core:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-cucumber:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-junit5:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-screenplay:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-screenplay-webdriver:${serenityCoreVersion}",
            "net.serenity-bdd:serenity-ensure:${serenityCoreVersion}",
            "org.junit.jupiter:junit-jupiter-api:${junitVersion}",
            "org.junit.jupiter:junit-jupiter-engine:${junitVersion}",
            "org.assertj:assertj-core:${assertJVersion}",
            "org.projectlombok:lombok:${lombokVersion}",
            "ch.qos.logback:logback-classic:${logbackVersion}"
}

test {
    useJUnitPlatform()
    testLogging.showStandardStreams = true
    systemProperties System.getProperties()
}
gradle.startParameter.continueOnFailure = true

serenity {
    reports = ["single-page-html"]

    // // Specify the root package of any JUnit acceptance tests
    testRoot="starter"
}

test.finalizedBy(aggregate)
