#
#Sat Mar 21 19:45:38 IST 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--guest, --incognito, --disable-sync, --no-first-run, --disable-save-password-bubble, --disable-notifications, --password-store\=basic, --disable-features\=PasswordLeakDetection,PasswordCheck,PasswordCheckup,PasswordManagerOnboarding,AutofillServerCommunication, remote-allow-origins\=*], extensions\=[], prefs\={profile.default_content_setting_values.notifications\=2, credentials_enable_service\=false, autofill.credit_card_enabled\=false, autofill.profile_enabled\=false, safebrowsing.enabled\=false, profile.password_manager_enabled\=false, profile.password_manager_leak_detection\=false}}
